/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary-dim': '#57514e',
        primary: '#635d5a',
        'on-background': '#31332c',
        'surface-variant': '#e2e3d9',
        'on-secondary-fixed-variant': '#635a52',
        'on-secondary-fixed': '#463e37',
        'surface-container-high': '#e8e9e0',
        'surface-bright': '#fbf9f4',
        surface: '#fbf9f4',
        'outline-variant': '#b1b3a9',
        'on-primary': '#fff6f1',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-container': '#64523c',
        'tertiary-fixed-dim': '#f0d6b9',
        'on-surface': '#31332c',
        'inverse-on-surface': '#9e9d99',
        'on-tertiary-fixed-variant': '#6f5c45',
        'surface-container': '#efeee6',
        'secondary-fixed': '#ede0d6',
        'primary-container': '#e9e1dc',
        error: '#9e422c',
        'on-tertiary-fixed': '#51402b',
        'tertiary-dim': '#62503a',
        'on-error': '#fff7f6',
        'on-primary-fixed': '#433e3b',
        'secondary-dim': '#5a524a',
        'secondary-container': '#ede0d6',
        outline: '#797c73',
        'surface-tint': '#635d5a',
        'tertiary-fixed': '#fee4c6',
        'primary-fixed-dim': '#dbd3ce',
        'surface-dim': '#d9dbcf',
        'on-surface-variant': '#5e6058',
        background: '#fbf9f4',
        'surface-container-highest': '#e2e3d9',
        secondary: '#665e55',
        'on-primary-fixed-variant': '#605a57',
        'on-primary-container': '#56514d',
        tertiary: '#6f5c45',
        'on-error-container': '#742410',
        'on-tertiary': '#fff7f3',
        'error-dim': '#5c1202',
        'primary-fixed': '#e9e1dc',
        'inverse-surface': '#0e0e0c',
        'tertiary-container': '#fee4c6',
        'error-container': '#fe8b70',
        'on-secondary': '#fff7f3',
        'on-secondary-container': '#595048',
        'surface-container-low': '#f5f4ed',
        'inverse-primary': '#ffffff',
        'secondary-fixed-dim': '#dfd2c8',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['"Noto Serif"', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(4px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-up-fade': {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'toast-in': {
          '0%': { opacity: '0', transform: 'translateY(16px) scale(0.96)' },
          '60%': { opacity: '1', transform: 'translateY(-2px) scale(1.01)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        'pop-in': {
          '0%': { opacity: '0', transform: 'scale(0.92)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'tick': {
          '0%': { opacity: '0.45', transform: 'translateY(-2px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'live-pulse': {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '0.35', transform: 'scale(0.85)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 280ms cubic-bezier(0.22, 1, 0.36, 1) both',
        'slide-up-fade': 'slide-up-fade 320ms cubic-bezier(0.22, 1, 0.36, 1) both',
        'toast-in': 'toast-in 360ms cubic-bezier(0.22, 1, 0.36, 1) both',
        'pop-in': 'pop-in 220ms cubic-bezier(0.34, 1.56, 0.64, 1) both',
        'tick': 'tick 220ms cubic-bezier(0.22, 1, 0.36, 1) both',
        'live-pulse': 'live-pulse 1.5s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
